# Use an official Nginx runtime as a parent image
FROM nginx:latest

# Set the working directory to /app
WORKDIR /app

# Remove default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Copy the Symfony web app to the container
COPY ./web /app

# Make port 80 available to the world outside this container
EXPOSE 80
